# app/db/models/recommendation.py

from sqlalchemy import Column, String, Text, Float, Boolean, ForeignKey, Index, JSON
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.db.base import UUIDBaseModel


class Recommendation(UUIDBaseModel):
    """
    AI-generated actionable recommendations for founders.
    Generated by analyzing metric trends and growth signals.
    """
    __tablename__ = "recommendations"

    organization_id = Column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Content ───────────────────────────────────────────────────────────────
    category = Column(String, nullable=False, index=True)
    # growth | retention | revenue | ai_cost | activation | churn_risk

    title = Column(String, nullable=False)
    summary = Column(Text, nullable=False)
    detail = Column(Text, nullable=True)
    action_items = Column(JSON, nullable=True)   # list of action strings

    # ── Scoring ───────────────────────────────────────────────────────────────
    impact_score = Column(Float, default=0.0)    # 0-10: expected business impact
    urgency_score = Column(Float, default=0.0)   # 0-10: how time-sensitive
    confidence = Column(Float, default=0.0)      # 0-1: model confidence

    # ── Status ────────────────────────────────────────────────────────────────
    is_dismissed = Column(Boolean, default=False)
    is_actioned = Column(Boolean, default=False)

    # ── Meta ─────────────────────────────────────────────────────────────────
    data_snapshot = Column(JSON, nullable=True)  # metrics used to generate this
    model_used = Column(String, nullable=True)

    __table_args__ = (
        Index("idx_rec_org_category", "organization_id", "category"),
    )
