"""add data uploads table

Revision ID: cd098e7e0185
Revises: 148a2fcef472
Create Date: 2026-03-14 21:53:18.861648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd098e7e0185'
down_revision: Union[str, Sequence[str], None] = '148a2fcef472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_uploads',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('upload_type', sa.String(length=50), nullable=False),
    sa.Column('ad_platform', sa.String(length=50), nullable=True),
    sa.Column('detected_columns', sa.JSON(), nullable=True),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parse_warnings', sa.JSON(), nullable=True),
    sa.Column('data_date_from', sa.String(length=20), nullable=True),
    sa.Column('data_date_to', sa.String(length=20), nullable=True),
    sa.Column('ai_insight_quick', sa.Text(), nullable=True),
    sa.Column('ai_insight_deep', sa.Text(), nullable=True),
    sa.Column('ai_insight_json', sa.JSON(), nullable=True),
    sa.Column('ai_model_quick', sa.String(length=50), nullable=True),
    sa.Column('ai_model_deep', sa.String(length=50), nullable=True),
    sa.Column('ai_tokens_used', sa.Integer(), nullable=True),
    sa.Column('ai_cost_usd', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_uploads_id'), 'data_uploads', ['id'], unique=False)
    op.create_index(op.f('ix_data_uploads_organization_id'), 'data_uploads', ['organization_id'], unique=False)
    op.create_table('ad_campaign_metrics',
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('campaign_id', sa.String(length=200), nullable=True),
    sa.Column('campaign_name', sa.String(length=500), nullable=True),
    sa.Column('ad_set_name', sa.String(length=500), nullable=True),
    sa.Column('ad_name', sa.String(length=500), nullable=True),
    sa.Column('objective', sa.String(length=100), nullable=True),
    sa.Column('row_date', sa.String(length=20), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('cost_per_conversion', sa.Float(), nullable=True),
    sa.Column('revenue_attributed', sa.Float(), nullable=True),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('video_views', sa.Integer(), nullable=True),
    sa.Column('video_completions', sa.Integer(), nullable=True),
    sa.Column('video_completion_rate', sa.Float(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['data_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_campaign_metrics_id'), 'ad_campaign_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_ad_campaign_metrics_organization_id'), 'ad_campaign_metrics', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ad_campaign_metrics_upload_id'), 'ad_campaign_metrics', ['upload_id'], unique=False)
    op.create_table('uploaded_rows',
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('row_date', sa.String(length=20), nullable=True),
    sa.Column('mrr', sa.Float(), nullable=True),
    sa.Column('arr', sa.Float(), nullable=True),
    sa.Column('new_mrr', sa.Float(), nullable=True),
    sa.Column('churned_mrr', sa.Float(), nullable=True),
    sa.Column('expansion_mrr', sa.Float(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('new_customers', sa.Integer(), nullable=True),
    sa.Column('churned_customers', sa.Integer(), nullable=True),
    sa.Column('total_customers', sa.Integer(), nullable=True),
    sa.Column('churn_rate', sa.Float(), nullable=True),
    sa.Column('arpu', sa.Float(), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('new_users', sa.Integer(), nullable=True),
    sa.Column('pageviews', sa.Integer(), nullable=True),
    sa.Column('bounce_rate', sa.Float(), nullable=True),
    sa.Column('session_duration', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('medium', sa.String(length=100), nullable=True),
    sa.Column('campaign', sa.String(length=200), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['data_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_rows_id'), 'uploaded_rows', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_rows_organization_id'), 'uploaded_rows', ['organization_id'], unique=False)
    op.create_index(op.f('ix_uploaded_rows_upload_id'), 'uploaded_rows', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_rows_upload_id'), table_name='uploaded_rows')
    op.drop_index(op.f('ix_uploaded_rows_organization_id'), table_name='uploaded_rows')
    op.drop_index(op.f('ix_uploaded_rows_id'), table_name='uploaded_rows')
    op.drop_table('uploaded_rows')
    op.drop_index(op.f('ix_ad_campaign_metrics_upload_id'), table_name='ad_campaign_metrics')
    op.drop_index(op.f('ix_ad_campaign_metrics_organization_id'), table_name='ad_campaign_metrics')
    op.drop_index(op.f('ix_ad_campaign_metrics_id'), table_name='ad_campaign_metrics')
    op.drop_table('ad_campaign_metrics')
    op.drop_index(op.f('ix_data_uploads_organization_id'), table_name='data_uploads')
    op.drop_index(op.f('ix_data_uploads_id'), table_name='data_uploads')
    op.drop_table('data_uploads')
    # ### end Alembic commands ###
